import {NextResponse} from "next/server";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {createServiceOrderPdf} from "@/lib/service-order-pdf.mjs";

export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){
 const{id}=await params;const supabase=await createSupabaseServerClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Não autorizado"},{status:401});
 const{data:service,error}=await supabase.from("services").select("id,company_id,service_number,quantity,scheduled_delivery_date,delivered_at,deadline_date,collected_at,status,amount,payment_method,payment_status,notes,created_at,clients(name,document,phone,email),client_addresses(address,number,complement,neighborhood,city,state,zip_code),service_payments(id,amount,payment_method),service_dumpsters(id,delivery_scheduled_at,delivered_at,deadline_at,collected_at,status,created_at)").eq("id",id).order("created_at",{referencedTable:"service_dumpsters",ascending:true}).single();
 if(error||!service){console.error("[OS/PDF] Serviço",error);return NextResponse.json({error:"Ordem de Serviço não encontrada"},{status:404})}
 const{data:company,error:companyError}=await supabase.from("companies").select("id,name,document,address,number,neighborhood,city,state,zip_code,phone,whatsapp,logo_url").eq("id",service.company_id).single();if(companyError||!company){console.error("[OS/PDF] Empresa",companyError);return NextResponse.json({error:"Dados da empresa não encontrados"},{status:404})}
 const client=service.clients as unknown as {name:string;document:string|null;phone:string;email:string|null};const address=service.client_addresses as unknown as {address:string;number:string|null;complement:string|null;neighborhood:string|null;city:string;state:string;zip_code:string|null};const payments=(service.service_payments||[]) as {id:string;amount:number|string;payment_method:string}[];const received=payments.reduce((sum,payment)=>sum+Number(payment.amount),0);const balance=Math.max(0,Number(service.amount)-received);const methods=[...new Set(payments.map(payment=>payment.payment_method))];
 const bytes=await createServiceOrderPdf({...service,client_name:client.name,client_document:client.document,client_phone:client.phone,client_email:client.email,work_address:address.address,work_number:address.number,work_complement:address.complement,work_neighborhood:address.neighborhood,work_city:address.city,work_state:address.state,work_zip_code:address.zip_code,company_name:company.name,company_document:company.document,company_address:company.address,company_number:company.number,company_neighborhood:company.neighborhood,company_city:company.city,company_state:company.state,company_zip_code:company.zip_code,company_phone:company.phone,company_whatsapp:company.whatsapp,company_logo_url:company.logo_url,received,balance,payment_method:methods.length?methods.join(", "):service.payment_method,payment_status:balance===0?"paid":received>0?"partial":"pending"});
 return new Response(bytes as BodyInit,{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="${service.service_number}.pdf"`,"Cache-Control":"private, no-store"}});
}
