import {notFound,redirect} from "next/navigation";
import {AppShell} from "@/components/shell";
import {ServiceActions} from "@/components/service-actions";
import {ServiceDeadlineCard} from "@/components/service-deadline-card";
import {PaymentRegistration} from "@/components/payment-registration";
import {PaymentDetailsButton,ReceiptActionButton} from "@/components/view-actions";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {money,date,labels,paymentLabels,ServiceStatus,PaymentStatus} from "@/lib/erp";

type Payment={id:string;amount:number|string;payment_method:string;paid_at:string;notes:string|null;created_by_name:string|null;receipts:{id:string}[]};
type Row={id:string;service_number:string;quantity:number;scheduled_delivery_date:string;delivered_at:string|null;deadline_date:string|null;collected_at:string|null;status:ServiceStatus;amount:number|string;payment_status:PaymentStatus;notes:string|null;clients:{name:string;phone:string}|null;client_addresses:{address:string;number:string|null;neighborhood:string|null;city:string;state:string}|null;service_payments:Payment[]};
export const dynamic="force-dynamic";

export default async function Detalhe({params}:{params:Promise<{id:string}>}){
 const{id}=await params;const sb=await createSupabaseServerClient();const{data:{user}}=await sb.auth.getUser();if(!user)redirect("/login");
 const{data,error}=await sb.from("services").select("id,service_number,quantity,scheduled_delivery_date,delivered_at,deadline_date,collected_at,status,amount,payment_status,notes,clients(name,phone),client_addresses(address,number,neighborhood,city,state),service_payments(id,amount,payment_method,paid_at,notes,created_by_name,receipts(id))").eq("id",id).order("paid_at",{referencedTable:"service_payments",ascending:false}).single();
 if(error){if(error.code==="PGRST116")notFound();console.error("[servicos/detalhe] Consulta",error);throw new Error("Não foi possível carregar a OS.")}
 const service=data as unknown as Row;const payments=service.service_payments||[];const received=payments.reduce((sum,payment)=>sum+Number(payment.amount),0);const balance=Math.max(0,Number(service.amount)-received);const clientName=service.clients?.name||"Cliente";const address=service.client_addresses?`${service.client_addresses.address}${service.client_addresses.number?`, ${service.client_addresses.number}`:""} · ${service.client_addresses.neighborhood?`${service.client_addresses.neighborhood} · `:""}${service.client_addresses.city}/${service.client_addresses.state}`:"—";
 return <AppShell title={`Serviços / ${service.service_number}`}><div className="heading"><div><h1>{service.service_number}</h1><div className="sub">Ordem de serviço de {clientName}</div></div><span className={`status ${service.status}`}>{labels[service.status]}</span></div><div className="grid"><div className="card wide"><h2>{clientName}</h2><p>{service.clients?.phone||"—"}</p><p>{address}</p></div><div className={`card financeCard ${balance>0?"hasBalance":"isPaid"}`}><div className="financeCardHeader"><div><span className="eyebrow">Financeiro</span><h2>Resumo do pagamento</h2></div><span className={`status ${balance===0?"paid":service.payment_status}`}>{balance===0?"Pago":paymentLabels[service.payment_status]}</span></div><div className="financeRows"><div><span>Valor total</span><strong>{money(service.amount)}</strong></div><div><span>Recebido</span><strong className="receivedValue">{money(received)}</strong></div><div className="balanceRow"><span>Saldo a receber</span><strong>{money(balance)}</strong></div></div><div className="financeAction"><PaymentRegistration serviceId={service.id} balance={balance}/>{balance===0&&<span className="paidMessage">Pagamento integral recebido</span>}</div></div><ServiceDeadlineCard status={service.status} deliveredAt={service.delivered_at} collectedAt={service.collected_at} initialNow={new Date().toISOString()}/></div><section className="section card"><h2>Operação</h2><p>Entrega prevista: {date(service.scheduled_delivery_date)} · Quantidade: {service.quantity}</p>{service.notes&&<p className="sub">{service.notes}</p>}<ServiceActions id={service.id} status={service.status}/></section><section className="section"><div className="sectionTitle"><h2>Pagamentos</h2></div>{payments.length===0?<div className="card emptyState">Nenhum pagamento registrado.</div>:<div className="tableWrap paymentsTable"><table><thead><tr><th>Data</th><th>Valor</th><th>Forma</th><th>Observação</th><th>Registrado por</th><th>Ações</th></tr></thead><tbody>{payments.map(payment=>{const userName=payment.created_by_name||"Sistema";const receiptId=payment.receipts?.[0]?.id||null;return <tr key={payment.id}><td>{new Date(payment.paid_at).toLocaleString("pt-BR")}</td><td><b>{money(payment.amount)}</b></td><td>{payment.payment_method}</td><td>{payment.notes||"—"}</td><td>{userName}</td><td><div className="actionGroup"><PaymentDetailsButton payment={{id:payment.id,receiptId,amount:payment.amount,paidAt:payment.paid_at,method:payment.payment_method,notes:payment.notes,userName,serviceNumber:service.service_number,clientName}}/><ReceiptActionButton paymentId={payment.id} initialReceiptId={receiptId}/></div></td></tr>})}</tbody></table></div>}</section></AppShell>;
}
