import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {AppShell} from "@/components/shell";
import {ViewServiceLink} from "@/components/view-actions";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {labels,paymentLabels,money,date,ServiceStatus,PaymentStatus} from "@/lib/erp";

type ServiceRow={id:string;service_number:string;quantity:number;scheduled_delivery_date:string;deadline_date:string|null;status:ServiceStatus;amount:number|string;payment_status:PaymentStatus;service_payments:{amount:number|string}[];service_dumpsters:{status:string;delivery_scheduled_at:string;deadline_at:string|null}[];client_addresses:{address:string;number:string|null;city:string}|null};
export const dynamic="force-dynamic";

export default async function Cliente({params}:{params:Promise<{id:string}>}){
 const{id}=await params;const supabase=await createSupabaseServerClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const[{data:client,error:clientError},{data:services,error:servicesError},{data:addresses,error:addressesError}]=await Promise.all([supabase.from("clients").select("id,name,document,phone,email,address,city,notes").eq("id",id).single(),supabase.from("services").select("id,service_number,quantity,scheduled_delivery_date,deadline_date,status,amount,payment_status,service_payments(amount),service_dumpsters(status,delivery_scheduled_at,deadline_at),client_addresses(address,number,city)").eq("client_id",id).order("created_at",{ascending:false}),supabase.from("client_addresses").select("id,address,number,complement,neighborhood,city,state").eq("client_id",id).order("created_at",{ascending:false})]);
 if(clientError){if(clientError.code==="PGRST116")notFound();console.error("[clientes/detalhe] Cliente",clientError);throw new Error("Não foi possível carregar o cliente.")}
 if(servicesError||addressesError){console.error("[clientes/detalhe] Relacionamentos",{servicesError,addressesError});throw new Error("Não foi possível carregar o histórico do cliente.")}
 const rows=(services||[]) as unknown as ServiceRow[];const total=rows.filter(service=>service.status==="completed").reduce((sum,service)=>sum+Number(service.amount||0),0);const pending=rows.filter(service=>service.status!=="cancelled").reduce((sum,service)=>sum+Math.max(0,Number(service.amount)-(service.service_payments||[]).reduce((received,payment)=>received+Number(payment.amount),0)),0);
 return <AppShell title="Clientes / Detalhes"><div className="heading"><div><h1>{client.name}</h1><div className="sub">{client.document||"Sem documento"} · {client.phone}{client.email?` · ${client.email}`:""}</div></div><Link className="btn secondary" href={`/clientes/${id}/editar`}>Editar cliente</Link></div><div className="grid"><div className="card metric"><div><label>Total gasto</label><strong>{money(total)}</strong></div></div><div className="card metric"><div><label>Valor pendente</label><strong>{money(pending)}</strong></div></div><div className="card metric"><div><label>Quantidade de serviços</label><strong>{rows.length}</strong></div></div></div><section className="section"><div className="sectionTitle"><div><h2>Histórico de serviços</h2><p className="sub">Uma linha por OS, com o resumo de todas as caçambas vinculadas.</p></div></div>{rows.length===0?<div className="card emptyState">Nenhum serviço cadastrado para este cliente.</div>:<div className="tableWrap clientServicesTable"><table><thead><tr><th>OS</th><th>Endereço</th><th>Qtd.</th><th>Entrega</th><th>Prazo / data limite</th><th>Status</th><th>Valor total</th><th>Recebido</th><th>Saldo</th><th>Pagamento</th><th>Ações</th></tr></thead><tbody>{rows.map(service=>{const received=(service.service_payments||[]).reduce((sum,payment)=>sum+Number(payment.amount),0),balance=Math.max(0,Number(service.amount)-received),dumpsters=service.service_dumpsters||[],delivered=dumpsters.filter(item=>["delivered","waiting_collection"].includes(item.status)).length,scheduled=dumpsters.filter(item=>item.status==="scheduled").length;return <tr key={service.id}><td><b>{service.service_number}</b></td><td>{service.client_addresses?`${service.client_addresses.address}${service.client_addresses.number?`, ${service.client_addresses.number}`:""} · ${service.client_addresses.city}`:"—"}</td><td>{dumpsters.filter(item=>item.status!=="cancelled").length} caçamba{dumpsters.filter(item=>item.status!=="cancelled").length===1?"":"s"}<div className="sub">{delivered} entregues · {scheduled} agendadas</div></td><td>{date(service.scheduled_delivery_date)}</td><td>Ver prazos individuais</td><td><span className={`status ${service.status}`}>{labels[service.status]}</span></td><td>{money(service.amount)}</td><td>{money(received)}</td><td>{money(balance)}</td><td><span className={`status ${service.payment_status}`}>{paymentLabels[service.payment_status]}</span></td><td><ViewServiceLink id={service.id} label="Ver OS"/></td></tr>})}</tbody></table></div>}</section><section className="section"><h2>Endereços e obras</h2><div className="card">{addresses?.length?addresses.map(address=><p key={address.id}>{address.address}{address.number?`, ${address.number}`:""}{address.complement?` · ${address.complement}`:""} · {address.neighborhood?`${address.neighborhood} · `:""}{address.city}/{address.state}</p>):<p className="sub">Nenhum endereço de obra cadastrado.</p>}</div></section></AppShell>;
}
