"use client";
import {useState} from "react";
import {Building2,ShieldCheck} from "lucide-react";
import {Company,companyInitials} from "@/lib/company";
import {createSupabaseBrowserClient} from "@/lib/supabase/client";

const fields:[keyof Company,string,string?][]=[["name","Nome da empresa"],["document","CNPJ"],["address","Endereço"],["number","Número"],["neighborhood","Bairro"],["city","Cidade"],["state","Estado"],["zip_code","CEP"],["phone","Telefone"],["whatsapp","WhatsApp"],["email","E-mail","email"],["logo_url","URL da logo","url"]];
export function CompanySettingsForm({initialCompany,initialLowThreshold}:{initialCompany:Company;initialLowThreshold:number}){
 const[company,setCompany]=useState(initialCompany);const[lowThreshold,setLowThreshold]=useState(initialLowThreshold);const[saving,setSaving]=useState(false);const[saved,setSaved]=useState(false);const[error,setError]=useState("");
 function change(key:keyof Company,value:string){setCompany(current=>({...current,[key]:value}));setSaved(false)}
 async function save(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");const sb=createSupabaseBrowserClient();const payload={name:company.name,document:company.document||null,address:company.address||null,number:company.number||null,neighborhood:company.neighborhood||null,city:company.city||null,state:company.state||null,zip_code:company.zip_code||null,phone:company.phone||null,whatsapp:company.whatsapp||null,email:company.email||null,logo_url:company.logo_url||null};const[companyResult,thresholdResult]=await Promise.all([sb.from("companies").update(payload).eq("id",company.id!),sb.from("settings").upsert({company_id:company.id!,key:"low_dumpster_threshold",value:lowThreshold},{onConflict:"company_id,key"})]);if(companyResult.error||thresholdResult.error){console.error("[configurações] salvar",{companyError:companyResult.error,thresholdError:thresholdResult.error});setError(companyResult.error?.message||thresholdResult.error?.message||"Não foi possível salvar.")}else setSaved(true);setSaving(false)}
 return <><div className="heading"><div><h1>Configurações da Empresa</h1><div className="sub">Fonte central para ordens de serviço, PDFs, comprovantes, documentos e alertas.</div></div><span className="roleBadge"><ShieldCheck size={14}/>Acesso de administrador</span></div><form className="card" onSubmit={save}><div className="settingsHeader"><div className="logoPreview">{company.logo_url?<img src={company.logo_url} alt="Prévia da logo"/>:<><Building2 size={24}/><span>{companyInitials(company.name)}</span></>}</div><div><h2 style={{margin:"0 0 5px"}}>{company.name}</h2><div className="sub">CNPJ {company.document||"não informado"}</div></div></div><div className="formGrid">{fields.map(([key,label,type])=><div className={`field ${key==="name"||key==="address"||key==="logo_url"?"full":""}`} key={key}><label htmlFor={key}>{label}{key==="name"?" *":""}</label><input id={key} type={type||"text"} required={key==="name"} value={company[key]||""} onChange={event=>change(key,event.target.value)}/></div>)}<div className="field"><label htmlFor="lowThreshold">Alerta de baixa disponibilidade</label><input id="lowThreshold" type="number" min={0} step={1} required value={lowThreshold} onChange={event=>{setLowThreshold(Math.max(0,Number(event.target.value)));setSaved(false)}}/><small className="sub">Notificar administradores quando a disponibilidade for igual ou inferior a este número.</small></div></div><div className="saveBar"><button className="btn" disabled={saving}>{saving?"Salvando...":"Salvar configurações"}</button>{saved&&<span className="success">Configurações salvas.</span>}{error&&<span className="deadline overdue">{error}</span>}</div></form></>;
}
