"use client";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {createSupabaseBrowserClient} from "@/lib/supabase/client";
import type {ServiceStatus} from "@/lib/erp";
type Address={id:string;address:string;number:string|null;city:string};type Client={id:string;name:string;client_addresses:Address[]};type Service={id:string;status:ServiceStatus;client_id:string;address_id:string;quantity:number;scheduled_delivery_date:string;amount:number|string;notes:string|null};
export function ServiceEditForm({service,clients,received}:{service:Service;clients:Client[];received:number}){
 const router=useRouter();const[clientId,setClientId]=useState(service.client_id);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const editable=service.status==="scheduled";const addresses=useMemo(()=>clients.find(c=>c.id===clientId)?.client_addresses||[],[clients,clientId]);
 async function submit(event:React.FormEvent<HTMLFormElement>){
  event.preventDefault();setSaving(true);setError("");const form=new FormData(event.currentTarget);const amount=editable?Number(form.get("amount")):Number(service.amount);
  if(amount<received){setError(`O valor não pode ser menor que o total já recebido (${received.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}).`);setSaving(false);return}
  const quantity=Number(form.get("quantity"));const delivery=String(form.get("delivery"));const payload=editable?{client_id:clientId,address_id:String(form.get("address_id")),quantity,scheduled_delivery_date:delivery,amount,notes:String(form.get("notes")||"").trim()||null}:{notes:String(form.get("notes")||"").trim()||null};const sb=createSupabaseBrowserClient();
  if(editable){const{data:projected,error:projectionError}=await sb.rpc("projected_dumpster_availability",{target_date:delivery,exclude_service_id:service.id});if(projectionError){setError(`Não foi possível validar a disponibilidade: ${projectionError.message}`);setSaving(false);return}if(quantity>Number(projected||0)){setError(`Capacidade insuficiente: ${quantity} solicitadas e ${Number(projected||0)} projetadas como disponíveis nessa data.`);setSaving(false);return}}
  const{error:updateError}=await sb.from("services").update(payload).eq("id",service.id);if(updateError){console.error("[servicos/editar] UPDATE",updateError);setError(updateError.message);setSaving(false);return}router.push(`/servicos/${service.id}`);router.refresh();
 }
 return <form className="card formGrid" onSubmit={submit}>{error&&<div className="notice formError full">{error}</div>}{!editable&&<div className="notice full">Após a entrega, os dados operacionais ficam protegidos. Somente observações administrativas podem ser alteradas.</div>}{editable&&<><div className="field full"><label>Cliente *</label><select value={clientId} onChange={e=>setClientId(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field full"><label>Endereço da obra *</label><select name="address_id" required defaultValue={service.address_id}>{addresses.map(a=><option key={a.id} value={a.id}>{a.address}{a.number?`, ${a.number}`:""} · {a.city}</option>)}</select></div><div className="field"><label>Quantidade *</label><input name="quantity" type="number" min="1" required defaultValue={service.quantity}/></div><div className="field"><label>Entrega prevista *</label><input name="delivery" type="date" required defaultValue={service.scheduled_delivery_date}/></div><div className="field"><label>Valor total *</label><input name="amount" type="number" min={received} step="0.01" required defaultValue={Number(service.amount)}/><small>Já recebido: {received.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</small></div></>}<div className="field full"><label>Observações</label><textarea name="notes" rows={4} defaultValue={service.notes||""}/></div><div className="full"><button className="btn" disabled={saving}>{saving?"Salvando...":"Salvar alterações"}</button> <button type="button" className="btn secondary" onClick={()=>router.back()}>Cancelar</button></div></form>;
}
