export type ServiceStatus="scheduled"|"delivered"|"waiting_collection"|"completed"|"cancelled";
export type PaymentStatus="pending"|"partial"|"paid";
export const labels:Record<ServiceStatus,string>={scheduled:"Agendado",delivered:"Entregue",waiting_collection:"Aguardando retirada",completed:"Finalizado",cancelled:"Cancelado"};
export const paymentLabels:Record<PaymentStatus,string>={pending:"Pendente",partial:"Parcial",paid:"Pago"};
export const money=(value:number|string|null|undefined)=>Number(value||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export const date=(value?:string|null)=>value?new Date(`${value.length===10?value+"T12:00:00":value}`).toLocaleDateString("pt-BR"):"—";
export function deadline(value?:string|null,deliveredAt?:string|null){if(!value&&!deliveredAt)return{label:"Prazo não iniciado",tone:""};const target=deliveredAt?new Date(deliveredAt).getTime()+7*86400000:new Date(`${value}T23:59:59`).getTime();const diff=target-Date.now();const span=(ms:number)=>{const days=Math.floor(ms/86400000);const hours=Math.floor((ms%86400000)/3600000);return days>0?`${days} ${days===1?"dia":"dias"} e ${hours}h`:`${hours}h`};if(diff<0)return{label:`Atrasado há ${-diff<3600000?"menos de 1h":span(-diff)}`,tone:"overdue"};if(diff<86400000)return{label:`Retirada em ${Math.max(1,Math.ceil(diff/3600000))}h`,tone:"danger"};return{label:`${span(diff)} restantes`,tone:""}}
export const todayInSaoPaulo=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
export const monthBounds=()=>{const parts=todayInSaoPaulo().split("-").map(Number);const start=`${parts[0]}-${String(parts[1]).padStart(2,"0")}-01`;const next=parts[1]===12?`${parts[0]+1}-01-01`:`${parts[0]}-${String(parts[1]+1).padStart(2,"0")}-01`;return{start,next}};
