import {PDFDocument,StandardFonts,rgb} from "pdf-lib";
const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const wrap=(text,font,size,max)=>{const words=String(text||"").trim().split(/\s+/).filter(Boolean);const lines=[];let line="";for(const rawWord of words){let word=rawWord;while(font.widthOfTextAtSize(word,size)>max){let part="";for(const char of word){if(font.widthOfTextAtSize(part+char,size)>max)break;part+=char}if(!part)break;if(line){lines.push(line);line=""}lines.push(part);word=word.slice(part.length)}if(!word)continue;const next=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(next,size)<=max)line=next;else{if(line)lines.push(line);line=word}}if(line)lines.push(line);return lines};
const limitedLines=(text,font,size,max,count)=>{const lines=wrap(text,font,size,max);if(lines.length<=count)return lines;const visible=lines.slice(0,count);let last=visible[count-1];while(last&&font.widthOfTextAtSize(`${last}…`,size)>max)last=last.slice(0,-1);visible[count-1]=`${last.trimEnd()}…`;return visible};
export async function createReceiptPdf(r){const doc=await PDFDocument.create();const page=doc.addPage([595.28,841.89]);const normal=await doc.embedFont(StandardFonts.Helvetica);const bold=await doc.embedFont(StandardFonts.HelveticaBold);const orange=rgb(.87,.27,.04),ink=rgb(.08,.12,.18),muted=rgb(.35,.4,.47),line=rgb(.78,.8,.83);let logo=null;if(r.company_logo_url){try{const response=await fetch(r.company_logo_url);if(response.ok){const bytes=await response.arrayBuffer();const type=response.headers.get("content-type")||"";logo=type.includes("png")?await doc.embedPng(bytes):await doc.embedJpg(bytes)}}catch{}}
 const drawText=(text,x,y,size=8,font=normal,color=ink)=>page.drawText(String(text||""),{x,y,size,font,color});const right=(text,x,y,size=8,font=normal,color=ink)=>drawText(text,x-font.widthOfTextAtSize(String(text),size),y,size,font,color);const label=(text,x,y)=>drawText(String(text).toUpperCase(),x,y,6.5,bold,muted);
 function copy(top,via){const left=30,rightX=565,width=535;let brandX=left;if(logo){page.drawImage(logo,{x:left,y:top-45,width:38,height:38});brandX=74}drawText(r.company_name,brandX,top-17,12,bold);drawText([r.company_document&&`CNPJ ${r.company_document}`,r.company_phone,r.company_whatsapp&&`WhatsApp ${r.company_whatsapp}`].filter(Boolean).join("  |  "),brandX,top-31,7,normal,muted);limitedLines(r.company_address,normal,7,360,2).forEach((text,index)=>drawText(text,brandX,top-42-index*8,7,normal,muted));right(via,rightX,top-12,7,bold,muted);right(r.receipt_number,rightX,top-29,12,bold,orange);page.drawLine({start:{x:left,y:top-57},end:{x:rightX,y:top-57},thickness:1,color:ink});
 label("Ordem de Serviço",left,top-70);drawText(r.service_number,left,top-82,8,bold);label("Data",205,top-70);drawText(new Date(r.paid_at).toLocaleString("pt-BR"),205,top-82,8,bold);label("Forma de pagamento",405,top-70);drawText(r.payment_method,405,top-82,8,bold);
 label("Cliente",left,top-99);limitedLines(r.client_name,bold,8,205,1).forEach(text=>drawText(text,left,top-111,8,bold));if(r.client_document){label("CPF/CNPJ",275,top-99);drawText(r.client_document,275,top-111,8,bold)}label("Telefone",430,top-99);drawText(r.client_phone,430,top-111,8,bold);label("Endereço da obra",left,top-128);limitedLines(r.work_address,bold,8,width,2).forEach((text,index)=>drawText(text,left,top-140-index*10,8,bold));
 page.drawRectangle({x:left,y:top-198,width,height:43,color:rgb(1,.965,.93),borderColor:orange,borderWidth:1});label("Valor recebido",left+12,top-169);drawText(money(r.amount),left+12,top-190,18,bold,orange);right(Number(r.remaining_balance)===0?"QUITADO":"PAGAMENTO PARCIAL",rightX-12,top-183,8,bold,Number(r.remaining_balance)===0?rgb(.08,.45,.22):orange);
 const receiptText=`Recebemos de ${r.client_name} a importância de ${money(r.amount)}, referente ao pagamento da Ordem de Serviço ${r.service_number}. ${Number(r.remaining_balance)>0?`Este recibo refere-se a pagamento parcial. Saldo restante: ${money(r.remaining_balance)}.`:"Pagamento integral. Ordem de Serviço quitada."}`;limitedLines(receiptText,normal,8,width,3).forEach((t,i)=>drawText(t,left,top-216-i*11,8));
 const fy=top-263;const cols=[["Valor total da OS",money(r.service_total)],["Este pagamento",money(r.amount)],["Total recebido",money(r.received_through_payment)],["Saldo restante",money(r.remaining_balance)]];cols.forEach((c,i)=>{const x=left+i*134;label(c[0],x,fy);drawText(c[1],x,fy-14,9,bold)});if(r.payment_notes)limitedLines(`Observação: ${r.payment_notes}`,normal,7,width,2).forEach((text,index)=>drawText(text,left,top-297-index*9,7,normal,muted));
 const sy=top-342;page.drawLine({start:{x:left+30,y:sy},end:{x:left+230,y:sy},thickness:.6,color:ink});page.drawLine({start:{x:left+305,y:sy},end:{x:rightX-30,y:sy},thickness:.6,color:ink});drawText(r.company_name,left+30+(200-bold.widthOfTextAtSize(r.company_name,7))/2,sy-11,7,bold);drawText("Cliente",left+305+(230-bold.widthOfTextAtSize("Cliente",7))/2,sy-11,7,bold)}
 copy(820,"1ª VIA");const cutY=421;for(let x=30;x<565;x+=8)page.drawLine({start:{x,y:cutY},end:{x:x+4,y:cutY},thickness:.6,color:muted});page.drawRectangle({x:260,y:cutY-7,width:76,height:14,color:rgb(1,1,1)});page.drawLine({start:{x:266,y:cutY+4},end:{x:274,y:cutY-4},thickness:1,color:muted});page.drawLine({start:{x:266,y:cutY-4},end:{x:274,y:cutY+4},thickness:1,color:muted});drawText("Corte aqui",278,cutY-3,7,bold,muted);copy(400,"2ª VIA");return doc.save()}
