import {DEMO_BATCH,addressIds,assertCompany,clientIds,context,fail,paymentIds,serviceIds} from "./demo-seed-data.mjs";
const DAY=86400000;const at=(offset,hour=12)=>new Date(Date.now()+offset*DAY).toISOString().slice(0,10)+`T${String(hour).padStart(2,"0")}:00:00-03:00`;const day=offset=>at(offset).slice(0,10);
const people=[
 ["João Ferreira","(11) 90000-1001","joao.ferreira@example.test","Jardim Primavera","Rua das Acácias","125","São Paulo","SP"],
 ["Mariana Costa","(11) 90000-1002","mariana.costa@example.test","Vila Nova","Avenida das Palmeiras","480","São Paulo","SP"],
 ["Carlos Almeida","(11) 90000-1003","carlos.almeida@example.test","Parque Central","Rua do Comércio","73","Guarulhos","SP"],
 ["Fernanda Souza","(11) 90000-1004","fernanda.souza@example.test","Jardim Europa","Alameda dos Ipês","912","Osasco","SP"],
 ["Construtora Horizonte","(11) 90000-1005","contato@horizonte.example.test","Centro","Avenida Industrial","1500","Barueri","SP"],
 ["RM Reformas","(11) 90000-1006","obras@rmreformas.example.test","Vila Progresso","Rua das Oficinas","340","Carapicuíba","SP"],
 ["Oliveira Engenharia","(11) 90000-1007","projetos@oliveira.example.test","Bela Vista","Rua Projetada","600","São Paulo","SP"],
 ["Prime Obras","(11) 90000-1008","atendimento@primeobras.example.test","Jardim América","Avenida dos Construtores","88","Cotia","SP"]
];
const specs=[
 {c:0,status:"collected",delivery:-18,delivered:-18,collected:-13,amount:450,method:"Pix",quantity:1},{c:1,status:"collected",delivery:-16,delivered:-16,collected:-10,amount:420,method:"Dinheiro",quantity:1},{c:4,status:"collected",delivery:-14,delivered:-14,collected:-7,amount:550,method:"Transferência",quantity:2},{c:5,status:"collected",delivery:-11,delivered:-11,collected:-5,amount:500,method:"Pix",quantity:1},
 {c:2,status:"delivered",delivery:-3,delivered:-3,amount:450,method:"Boleto",quantity:1},{c:6,status:"delivered",delivery:-2,delivered:-2,amount:550,method:"Transferência",quantity:2},{c:7,status:"delivered",delivery:-1,delivered:-1,amount:500,method:"Pix",quantity:1},
 {c:3,status:"waiting_collection",delivery:-8,delivered:-8,amount:420,method:"Dinheiro",quantity:1},{c:0,status:"waiting_collection",delivery:-7,delivered:-7,amount:350,method:"Pix",quantity:1},{c:4,status:"waiting_collection",delivery:-9,delivered:-9,amount:550,method:"Boleto",quantity:2},
 {c:1,status:"scheduled",delivery:0,amount:450,method:"Cartão",quantity:1},{c:5,status:"scheduled",delivery:1,amount:420,method:"Pix",quantity:1},{c:6,status:"scheduled",delivery:3,amount:500,method:"Transferência",quantity:2},{c:7,status:"scheduled",delivery:5,amount:550,method:"Boleto",quantity:1},{c:2,status:"cancelled",delivery:4,amount:350,method:"Pix",quantity:1}
];
async function run(){
 const{supabase,companyId}=context(),company=await assertCompany(supabase,companyId);const{count,error:checkError}=await supabase.from("services").select("id",{count:"exact",head:true}).eq("company_id",companyId).eq("demo_batch",DEMO_BATCH);if(checkError)throw new Error(`Execute a migration 20260816000100_demo_portfolio_identification.sql: ${checkError.message}`);if(count)throw new Error(`Já existem ${count} OS do lote ${DEMO_BATCH}. Execute npm run seed:demo:clear antes.`);
 const clients=people.map((p,i)=>({id:clientIds[i],company_id:companyId,name:p[0],phone:p[1],email:p[2],document:i<4?`000.000.00${i+1}-00`:`00.000.00${i+1}/0001-00`,address:p[4],city:p[6],notes:`[${DEMO_BATCH}] Cliente fictício`,demo_batch:DEMO_BATCH}));let result=await supabase.from("clients").insert(clients);if(result.error)throw result.error;
 const addresses=people.map((p,i)=>({id:addressIds[i],company_id:companyId,client_id:clientIds[i],address:p[4],number:p[5],complement:i%2?"Obra demonstrativa":null,neighborhood:p[3],city:p[6],state:p[7],zip_code:`0${i+1}000-000`,notes:`[${DEMO_BATCH}] Endereço fictício`}));result=await supabase.from("client_addresses").insert(addresses);if(result.error)throw result.error;
 const services=specs.map((s,i)=>({id:serviceIds[i],company_id:companyId,service_number:`OS-DEMO-${String(i+1).padStart(3,"0")}`,client_id:clientIds[s.c],address_id:addressIds[s.c],quantity:s.quantity,scheduled_delivery_date:day(s.delivery),status:"scheduled",amount:s.amount,payment_method:s.method,payment_status:"pending",notes:`[${DEMO_BATCH}] Serviço fictício`,demo_batch:DEMO_BATCH,created_at:at(s.delivery-2,9)}));result=await supabase.from("services").insert(services);if(result.error)throw result.error;
 for(let i=0;i<specs.length;i++){const s=specs[i],{data:units,error}=await supabase.from("service_dumpsters").select("id").eq("service_id",serviceIds[i]).order("created_at");if(error)throw error;const update={status:s.status,delivery_scheduled_at:at(s.delivery),delivered_at:s.delivered===undefined?null:at(s.delivered,10+i%5),deadline_at:s.delivered===undefined?null:at(s.delivered+7,10+i%5),collection_requested_at:s.status==="waiting_collection"?at(-1,8):null,collected_at:s.collected===undefined?null:at(s.collected,14+i%3)};for(const unit of units||[]){const response=await supabase.from("service_dumpsters").update(update).eq("id",unit.id);if(response.error)throw response.error}}
 const paymentSpecs=[{s:0,amount:450},{s:1,amount:420},{s:2,amount:550},{s:3,amount:250},{s:4,amount:200}];const payments=paymentSpecs.map((p,i)=>({id:paymentIds[i],company_id:companyId,service_id:serviceIds[p.s],amount:p.amount,payment_method:specs[p.s].method,paid_at:at(-10+i,15),notes:`[${DEMO_BATCH}] Pagamento fictício`,created_by:null}));result=await supabase.from("service_payments").insert(payments);if(result.error)throw result.error;
 console.log(`\n[DEMO] Seed concluído para ${company.name}.`);console.log(`- ${clients.length} clientes fictícios`);console.log(`- ${services.length} ordens de serviço`);console.log(`- ${services.reduce((sum,s)=>sum+s.quantity,0)} caçambas distribuídas`);console.log(`- ${payments.length} pagamentos; as 3 primeiras OS permitem emitir recibos`);console.log(`Lote: ${DEMO_BATCH}`);
}
run().catch(fail);
