import Link from "next/link";
import {redirect} from "next/navigation";
import {AppShell} from "@/components/shell";
import {ViewServiceLink} from "@/components/view-actions";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {money,date,deadline,labels,paymentLabels,monthBounds,ServiceStatus,PaymentStatus} from "@/lib/erp";
import {calculateDumpsterTiming,dumpsterDayKey} from "@/lib/dumpster-deadline";

type Params={status?:string;statuses?:string;date?:string;collection?:string;payment?:string;month?:string;payments?:string;overdue?:string;q?:string};
type Dumpster={id:string;delivery_scheduled_at:string;delivered_at:string|null;deadline_at:string|null;collected_at:string|null;status:string};
type Row={id:string;service_number:string;quantity:number;scheduled_delivery_date:string;delivered_at:string|null;deadline_date:string|null;status:ServiceStatus;amount:number|string;payment_status:PaymentStatus;created_at:string;clients:{name:string;phone:string}|null;client_addresses:{address:string;number:string|null;city:string}|null;service_payments:{amount:number|string;paid_at:string}[];service_dumpsters:Dumpster[]};
const filters=[{label:"Todos",href:""},{label:"Agendados",href:"?status=scheduled"},{label:"Entregues",href:"?status=delivered"},{label:"Aguardando retirada",href:"?status=waiting_collection"},{label:"Atrasados",href:"?overdue=1"},{label:"Finalizados",href:"?status=completed"},{label:"Cancelados",href:"?status=cancelled"},{label:"Pagamento pendente",href:"?payment=pending"},{label:"Pagamento parcial",href:"?payment=partial"},{label:"Pago",href:"?payment=paid"}];
export const dynamic="force-dynamic";

export default async function Servicos({searchParams}:{searchParams:Promise<Params>}){
 const params=await searchParams;const sb=await createSupabaseServerClient();const{data:{user}}=await sb.auth.getUser();if(!user)redirect("/login");
 const{data,error}=await sb.from("services").select("id,service_number,quantity,scheduled_delivery_date,delivered_at,deadline_date,status,amount,payment_status,created_at,clients(name,phone),client_addresses(address,number,city),service_payments(amount,paid_at),service_dumpsters(id,delivery_scheduled_at,delivered_at,deadline_at,collected_at,status)").order("created_at",{ascending:false});
 if(error){console.error("[servicos] Falha ao buscar serviços",error);throw new Error("Não foi possível carregar os serviços.")}
 let rows=(data||[]) as unknown as Row[];
 if(params.status)rows=rows.filter(s=>s.status===params.status);if(params.statuses){const statuses=params.statuses.split(",");rows=rows.filter(s=>statuses.includes(s.status))}if(params.date)rows=rows.filter(s=>(s.service_dumpsters||[]).some(d=>d.status==="scheduled"&&dumpsterDayKey(d.delivery_scheduled_at)===params.date));if(params.collection)rows=rows.filter(s=>(s.service_dumpsters||[]).some(d=>["delivered","waiting_collection"].includes(d.status)&&dumpsterDayKey(calculateDumpsterTiming(d).deadlineAt)===params.collection));if(params.overdue)rows=rows.filter(s=>(s.service_dumpsters||[]).some(d=>calculateDumpsterTiming(d).tone==="overdue"));if(params.payment)rows=rows.filter(s=>s.payment_status===params.payment);if(params.payments==="receivable")rows=rows.filter(s=>Number(s.amount)-(s.service_payments||[]).reduce((sum,p)=>sum+Number(p.amount),0)>0);if(params.payments==="month"){const{start,next}=monthBounds();rows=rows.filter(s=>(s.service_payments||[]).some(p=>p.paid_at>=start&&p.paid_at<next))}if(params.month==="current"){const{start,next}=monthBounds();rows=rows.filter(s=>s.created_at>=start&&s.created_at<next)}if(params.q){const q=params.q.toLowerCase();rows=rows.filter(s=>`${s.service_number} ${s.clients?.name||""} ${s.clients?.phone||""} ${s.client_addresses?.address||""}`.toLowerCase().includes(q))}
 const active=Object.values(params).some(Boolean),hidden=Object.entries(params).filter(([key])=>key!=="q"),currentQuery=new URLSearchParams(Object.entries(params).filter(([,value])=>Boolean(value)) as [string,string][]).toString();
 return <AppShell title="Serviços"><div className="heading"><div><h1>Serviços</h1><div className="sub">Controle entregas, prazos e retiradas.{active?` Filtro ativo · ${rows.length} resultado${rows.length===1?"":"s"}.`:""}</div></div><Link className="btn" href="/servicos/novo">+ Novo serviço</Link></div><div className="toolbar"><form action="/servicos" className="serviceSearch">{hidden.map(([key,value])=><input type="hidden" name={key} value={value} key={key}/>)}<input className="search" name="q" aria-label="Buscar serviços" placeholder="Buscar OS, cliente, telefone ou endereço" defaultValue={params.q||""}/><button className="btn secondary">Buscar</button></form>{active&&<Link className="btn secondary" href="/servicos">Limpar filtros</Link>}</div><div className="filters serviceFilters">{filters.map(filter=><Link className={`filter ${(!currentQuery&&!filter.href)||(filter.href&&currentQuery===filter.href.slice(1))?"on":""}`} href={`/servicos${filter.href}`} key={filter.label}>{filter.label}</Link>)}</div>{rows.length===0?<div className="card emptyState">Nenhum serviço encontrado para este filtro.</div>:<div className="tableWrap"><table><thead><tr><th>OS</th><th>Cliente / endereço</th><th>Qtd.</th><th>Entrega</th><th>Prazo das caçambas</th><th>Status</th><th>Pagamento</th><th>Valor</th><th>Ações</th></tr></thead><tbody>{rows.map(service=>{const address=service.client_addresses?`${service.client_addresses.address}${service.client_addresses.number?`, ${service.client_addresses.number}`:""} · ${service.client_addresses.city}`:"—",serviceDeadline=deadline(service.deadline_date,service.delivered_at);return <tr key={service.id}><td><b>{service.service_number}</b></td><td><b>{service.clients?.name||"—"}</b><div className="sub">{address}</div></td><td>{service.quantity} caçamba{service.quantity===1?"":"s"}</td><td>{date(service.scheduled_delivery_date)}</td><td className={`deadline ${serviceDeadline.tone}`}>{service.status==="completed"?"Retirado":service.status==="cancelled"?"Cancelado":serviceDeadline.label}</td><td><span className={`status ${service.status}`}>{labels[service.status]}</span></td><td><span className={`status ${service.payment_status}`}>{paymentLabels[service.payment_status]}</span></td><td><b>{money(service.amount)}</b></td><td><ViewServiceLink id={service.id}/></td></tr>})}</tbody></table></div>}</AppShell>;
}
