import Link from "next/link";
import {redirect} from "next/navigation";
import {AppShell} from "@/components/shell";
import {ServiceActions} from "@/components/service-actions";
import {ViewServiceLink} from "@/components/view-actions";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {date,deadline,labels,money,paymentLabels,todayInSaoPaulo,ServiceStatus,PaymentStatus} from "@/lib/erp";

type Params={view?:string;date?:string;month?:string;q?:string};
type Row={id:string;service_number:string;quantity:number;scheduled_delivery_date:string;delivered_at:string|null;deadline_date:string|null;status:ServiceStatus;amount:number|string;payment_status:PaymentStatus;clients:{name:string;phone:string}|null;client_addresses:{address:string;number:string|null;city:string;state:string}|null};
const zone="America/Sao_Paulo";
const dayKey=(value:Date|string)=>new Intl.DateTimeFormat("en-CA",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit"}).format(typeof value==="string"?new Date(value):value);
const addDays=(key:string,n:number)=>{const d=new Date(`${key}T12:00:00-03:00`);d.setDate(d.getDate()+n);return dayKey(d)};
const withdrawalKey=(s:Row)=>s.delivered_at?dayKey(new Date(new Date(s.delivered_at).getTime()+7*86400000)):s.deadline_date;
const address=(s:Row)=>s.client_addresses?`${s.client_addresses.address}${s.client_addresses.number?`, ${s.client_addresses.number}`:""} · ${s.client_addresses.city}/${s.client_addresses.state}`:"—";

function OperationList({title,rows}:{title:string;rows:Row[]}){return <section className="agendaSection"><div className="sectionTitle"><h2>{title}</h2><span className="agendaCount">{rows.length}</span></div>{rows.length===0?<div className="card emptyAgenda">Nenhuma operação.</div>:<div className="agendaList">{rows.map(s=>{const dl=deadline(s.deadline_date,s.delivered_at);return <article className={`card agendaItem ${dl.tone}`} key={s.id}><div className="agendaItemMain"><div className="agendaOs"><strong>{s.service_number}</strong><span className={`status ${s.status}`}>{labels[s.status]}</span></div><h3>{s.clients?.name||"Cliente"}</h3><p>{s.clients?.phone||"Sem telefone"} · {address(s)}</p><div className="agendaFacts"><span><b>{s.quantity}</b> caçamba{s.quantity===1?"":"s"}</span><span>{money(s.amount)}</span><span className={`status ${s.payment_status}`}>{paymentLabels[s.payment_status]}</span>{s.status==="scheduled"?<span>Entrega: {date(s.scheduled_delivery_date)}</span>:<span className={`deadline ${dl.tone}`}>{dl.label}</span>}</div></div><div className="agendaActions"><ViewServiceLink id={s.id}/><ServiceActions id={s.id} status={s.status} compact/></div></article>})}</div>}</section>}

export const dynamic="force-dynamic";
export default async function Agenda({searchParams}:{searchParams:Promise<Params>}){
 const params=await searchParams;const sb=await createSupabaseServerClient();const{data:{user}}=await sb.auth.getUser();if(!user)redirect("/login");
 const[{data:services,error},{data:setting}]=await Promise.all([sb.from("services").select("id,service_number,quantity,scheduled_delivery_date,delivered_at,deadline_date,status,amount,payment_status,clients(name,phone),client_addresses(address,number,city,state)").in("status",["scheduled","delivered","waiting_collection"]).order("scheduled_delivery_date"),sb.from("settings").select("value").eq("key","total_dumpsters").maybeSingle()]);
 if(error){console.error("[agenda] Serviços",error);throw new Error("Não foi possível carregar a Agenda.")}
 let rows=(services||[]) as unknown as Row[];if(params.q){const q=params.q.toLowerCase();rows=rows.filter(s=>`${s.service_number} ${s.clients?.name||""} ${s.clients?.phone||""} ${address(s)}`.toLowerCase().includes(q))}
 const today=todayInSaoPaulo(),tomorrow=addDays(today,1),weekEnd=addDays(today,7);const activeWithdrawals=rows.filter(s=>["delivered","waiting_collection"].includes(s.status));const scheduled=rows.filter(s=>s.status==="scheduled");
 const deliveriesToday=scheduled.filter(s=>s.scheduled_delivery_date===today),withdrawalsToday=activeWithdrawals.filter(s=>withdrawalKey(s)===today),overdue=activeWithdrawals.filter(s=>(withdrawalKey(s)||"9999")<today);
 const deliveriesTomorrow=scheduled.filter(s=>s.scheduled_delivery_date===tomorrow),withdrawalsTomorrow=activeWithdrawals.filter(s=>withdrawalKey(s)===tomorrow);
 const selected=params.date;const view=params.view||"today";let shownDeliveries:Row[]=[],shownWithdrawals:Row[]=[];
 if(selected){shownDeliveries=scheduled.filter(s=>s.scheduled_delivery_date===selected);shownWithdrawals=activeWithdrawals.filter(s=>withdrawalKey(s)===selected)}else if(view==="tomorrow"){shownDeliveries=deliveriesTomorrow;shownWithdrawals=withdrawalsTomorrow}else if(view==="week"){shownDeliveries=scheduled.filter(s=>s.scheduled_delivery_date>=today&&s.scheduled_delivery_date<weekEnd);shownWithdrawals=activeWithdrawals.filter(s=>(withdrawalKey(s)||"")>=today&&(withdrawalKey(s)||"")<weekEnd)}
 const total=Number(setting?.value||0);
 const committed=(key:string)=>rows.filter(s=>s.status==="scheduled"?s.scheduled_delivery_date<=key&&addDays(s.scheduled_delivery_date,7)>key:["delivered","waiting_collection"].includes(s.status)&&(withdrawalKey(s)||key)>key).reduce((sum,s)=>sum+s.quantity,0);const projected=(key:string)=>Math.max(0,total-committed(key));
 const days14=Array.from({length:14},(_,i)=>addDays(today,i));const month=params.month||today.slice(0,7);const first=new Date(`${month}-01T12:00:00-03:00`);const firstWeekday=first.getDay();const lastDay=new Date(first.getFullYear(),first.getMonth()+1,0).getDate();const cells=[...Array(firstWeekday).fill(null),...Array.from({length:lastDay},(_,i)=>`${month}-${String(i+1).padStart(2,"0")}`)];
 return <AppShell title="Agenda"><div className="heading"><div><h1>Agenda operacional</h1><div className="sub">Entregas, retiradas e reservas calculadas com dados reais das OS.</div></div><Link className="btn" href="/servicos/novo">+ Novo serviço</Link></div>
 <form className="agendaSearch" action="/agenda"><input className="search" name="q" placeholder="Buscar OS, cliente, telefone ou endereço" defaultValue={params.q||""}/><button className="btn secondary">Buscar</button></form>
 <nav className="agendaTabs"><Link className={view==="today"&&!selected?"on":""} href="/agenda?view=today">Hoje</Link><Link className={view==="tomorrow"&&!selected?"on":""} href="/agenda?view=tomorrow">Amanhã</Link><Link className={view==="week"&&!selected?"on":""} href="/agenda?view=week">Esta semana</Link><Link className={view==="month"||selected?"on":""} href="/agenda?view=month">Calendário mensal</Link></nav>
 <section className="todayOperation"><h2>Operação de hoje</h2><div className="agendaColumns"><OperationList title="Entregas de hoje" rows={deliveriesToday}/><OperationList title="Retiradas de hoje" rows={withdrawalsToday}/><OperationList title="Atrasados" rows={overdue}/></div></section>
 {view==="tomorrow"&&!selected&&<section className="agendaView"><div className="agendaTomorrowSummary"><b>{deliveriesTomorrow.reduce((n,s)=>n+s.quantity,0)} caçambas necessárias amanhã</b><span>{projected(tomorrow)} disponíveis projetadas após os compromissos</span></div><OperationList title="Entregas de amanhã" rows={deliveriesTomorrow}/><OperationList title="Retiradas de amanhã" rows={withdrawalsTomorrow}/></section>}
 {(view==="week"||selected)&&<section className="agendaView"><OperationList title={selected?`Entregas em ${date(selected)}`:"Entregas desta semana"} rows={shownDeliveries}/><OperationList title={selected?`Retiradas em ${date(selected)}`:"Retiradas desta semana"} rows={shownWithdrawals}/></section>}
 <section className="section"><div className="sectionTitle"><div><h2>Disponibilidade por dia</h2><p className="sub">Projeção dos próximos 14 dias considerando entregas, reservas e retiradas previstas.</p></div></div><div className="availabilityDays">{days14.map(key=>{const used=committed(key),available=projected(key),deliveryCount=scheduled.filter(s=>s.scheduled_delivery_date===key).length,deliveryQuantity=scheduled.filter(s=>s.scheduled_delivery_date===key).reduce((n,s)=>n+s.quantity,0),lowLimit=Math.max(3,Math.ceil(total*.1)),tone=available===0?"zero":available<=lowLimit?"low":"";return <Link className={`card availabilityDay ${tone} ${deliveryCount?"hasReservation":""}`} href={`/agenda?view=month&date=${key}`} key={key} aria-label={`${date(key)}: ${used} comprometidas, ${available} disponíveis projetadas`}><span>{key===today?"Hoje · ":key===tomorrow?"Amanhã · ":""}{date(key)}</span><strong>{used} comprometida{used===1?"":"s"}</strong><b>{available} disponíveis projetadas</b>{deliveryCount>0&&<small>{deliveryCount} entrega{deliveryCount===1?"":"s"} agendada{deliveryCount===1?"":"s"} · {deliveryQuantity} caçamba{deliveryQuantity===1?"":"s"}</small>}{tone&&<em>{available===0?"Capacidade esgotada":"Disponibilidade baixa"}</em>}</Link>})}</div></section>
 <section className="section calendarSection"><div className="sectionTitle"><h2>Calendário mensal</h2><form action="/agenda"><input type="hidden" name="view" value="month"/><input type="month" name="month" defaultValue={month}/><button className="btn secondary">Abrir mês</button></form></div><div className="calendarGrid">{["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"].map(x=><b className="calendarWeek" key={x}>{x}</b>)}{cells.map((key,i)=>key?<Link className={`calendarDay ${key===today?"today":""}`} href={`/agenda?view=month&month=${month}&date=${key}`} key={key}><strong>{Number(key.slice(-2))}</strong><span>{scheduled.filter(s=>s.scheduled_delivery_date===key).length} entregas</span><span>{activeWithdrawals.filter(s=>withdrawalKey(s)===key).length} retiradas</span><small>{scheduled.filter(s=>s.scheduled_delivery_date===key).reduce((n,s)=>n+s.quantity,0)} reservadas</small></Link>:<span className="calendarDay empty" key={`e${i}`}/>)}</div></section></AppShell>
}
