import Link from "next/link";
import {redirect} from "next/navigation";
import {AppShell} from "@/components/shell";
import {ViewDetailsIndicator,ViewServiceLink} from "@/components/view-actions";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {money,date,deadline,labels,todayInSaoPaulo,monthBounds,ServiceStatus,PaymentStatus} from "@/lib/erp";
import {CalendarCheck,Truck,Undo2,Container,Boxes,Wallet,TrendingUp,ArrowRight,type LucideIcon} from "lucide-react";

type Row={id:string;service_number:string;quantity:number;scheduled_delivery_date:string;deadline_date:string|null;status:ServiceStatus;amount:number|string;payment_status:PaymentStatus;created_at:string;clients:{name:string}|null;client_addresses:{address:string;number:string|null;city:string}|null;service_payments:{amount:number|string;paid_at:string}[]};
type Metric={label:string;value:string;href:string;Icon:LucideIcon;wide?:boolean};
export const dynamic="force-dynamic";

export default async function Dashboard(){
 const sb=await createSupabaseServerClient();const{data:{user}}=await sb.auth.getUser();if(!user)redirect("/login");
 const{data:profile,error:profileError}=await sb.from("profiles").select("company_id,role").eq("id",user.id).single();
 if(profileError||!profile){console.error("[dashboard] Profile",profileError);throw new Error("Não foi possível validar o perfil do usuário.")}
 const serviceFields=profile.role==="admin"?"id,service_number,quantity,scheduled_delivery_date,deadline_date,status,amount,payment_status,created_at,clients(name),client_addresses(address,number,city),service_payments(amount,paid_at)":"id,service_number,quantity,scheduled_delivery_date,deadline_date,status,created_at,clients(name),client_addresses(address,number,city)";
 const{data:raw,error:servicesError}=await sb.from("services").select(serviceFields).order("deadline_date",{ascending:true});
 if(servicesError){console.error("[dashboard] Serviços",servicesError);throw new Error("Não foi possível carregar o Dashboard.")}
 const rows=(raw||[]) as unknown as Row[];
 const[{data:setting,error:settingError},{data:company,error:companyError}]=await Promise.all([sb.from("settings").select("value").eq("company_id",profile.company_id).eq("key","total_dumpsters").maybeSingle(),sb.from("companies").select("name").eq("id",profile.company_id).maybeSingle()]);
 if(settingError)console.error("[dashboard] total_dumpsters",settingError);if(companyError)console.error("[dashboard] Empresa",companyError);
 const companyName=company?.name?.trim()||"Nova Tira Entulho";const total=Number(setting?.value||0);const today=todayInSaoPaulo();const{start,next}=monthBounds();
 const scheduled=rows.filter(service=>service.status==="scheduled");const deliveriesToday=scheduled.filter(service=>service.scheduled_delivery_date===today);const collectionToday=rows.filter(service=>service.deadline_date===today&&["delivered","waiting_collection"].includes(service.status));const atClients=rows.filter(service=>["delivered","waiting_collection"].includes(service.status));const reserved=scheduled.reduce((sum,service)=>sum+service.quantity,0);const inClients=atClients.reduce((sum,service)=>sum+service.quantity,0);const available=Math.max(0,total-reserved-inClients);
 const pending=profile.role==="admin"?rows.filter(service=>service.status!=="cancelled").reduce((sum,service)=>sum+Math.max(0,Number(service.amount)-(service.service_payments||[]).reduce((received,payment)=>received+Number(payment.amount),0)),0):0;const paidMonth=profile.role==="admin"?rows.flatMap(service=>service.service_payments||[]).filter(payment=>payment.paid_at>=start&&payment.paid_at<next).reduce((sum,payment)=>sum+Number(payment.amount),0):0;
 const operationalMetrics:Metric[]=[{label:"Serviços agendados",value:String(scheduled.length),href:"/servicos?status=scheduled",Icon:CalendarCheck},{label:"Entregas de hoje",value:String(deliveriesToday.length),href:`/servicos?status=scheduled&date=${today}`,Icon:Truck},{label:"Retiradas de hoje",value:String(collectionToday.length),href:`/servicos?collection=${today}`,Icon:Undo2},{label:"Caçambas em clientes",value:String(inClients),href:"/servicos?statuses=delivered,waiting_collection",Icon:Container},{label:"Caçambas disponíveis",value:String(available),href:"/disponibilidade",Icon:Boxes}];
 const financialMetrics:Metric[]=[{label:"Valores a receber",value:money(pending),href:"/servicos?payments=receivable",Icon:Wallet,wide:true},{label:"Faturamento do mês",value:money(paidMonth),href:"/servicos?payments=month",Icon:TrendingUp,wide:true}];
 const metrics=profile.role==="admin"?[...operationalMetrics,...financialMetrics]:operationalMetrics;
 const upcoming=rows.filter(service=>service.deadline_date&&["delivered","waiting_collection"].includes(service.status)).slice(0,10);
 return <AppShell title="Visão geral"><div className="heading"><div><h1>Olá, {companyName}!</h1><div className="sub">Acompanhe a operação da sua empresa hoje.</div></div><Link className="btn" href="/servicos/novo">+ Novo serviço</Link></div><div className="grid">{metrics.map(({label,value,href,Icon,wide})=><Link className={`card metric metricLink dashboardMetric ${wide?"wide":""}`} href={href} key={label} aria-label={`${label}: ${value}. Ver detalhes`}><div><label>{label}</label><strong>{value}</strong></div><span className="metricIcon categoryIcon"><Icon size={20}/></span><ViewDetailsIndicator/></Link>)}</div><section className="section"><div className="sectionTitle"><h2>Próximas retiradas</h2><Link href="/servicos?statuses=delivered,waiting_collection">Ver todos <ArrowRight size={13} style={{display:"inline"}}/></Link></div>{upcoming.length===0?<div className="card emptyState">Nenhuma retirada programada.</div>:<div className="tableWrap withdrawalsTable"><table><thead><tr><th>Cliente</th><th>Endereço</th><th>Entrega</th><th>Data limite</th><th>Prazo</th><th>Status</th><th>Ações</th></tr></thead><tbody>{upcoming.map(service=>{const serviceDeadline=deadline(service.deadline_date);const address=service.client_addresses?`${service.client_addresses.address}${service.client_addresses.number?`, ${service.client_addresses.number}`:""} · ${service.client_addresses.city}`:"—";return <tr className="clickableRow" key={service.id}><td><Link className="rowLink" href={`/servicos/${service.id}`} aria-label={`Abrir ${service.service_number} de ${service.clients?.name||"cliente"}`}><b>{service.clients?.name||"—"}</b></Link></td><td>{address}</td><td>{date(service.scheduled_delivery_date)}</td><td>{date(service.deadline_date)}</td><td className={`deadline ${serviceDeadline.tone}`}>{serviceDeadline.label}</td><td><span className={`status ${service.status}`}>{labels[service.status]}</span></td><td className="withdrawalActions"><ViewServiceLink id={service.id} label="Ver detalhes"/></td></tr>})}</tbody></table></div>}</section></AppShell>;
}
