import Link from "next/link";
import {redirect} from "next/navigation";
import {CalendarCheck,Truck,Undo2,Container,Wallet,TrendingUp,ArrowRight,type LucideIcon} from "lucide-react";
import {AppShell} from "@/components/shell";
import {ViewDetailsIndicator,ViewServiceLink} from "@/components/view-actions";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {calculateDumpsterTiming,dumpsterDayKey} from "@/lib/dumpster-deadline";
import {money,date,todayInSaoPaulo,monthBounds,PaymentStatus} from "@/lib/erp";
type Dumpster={id:string;delivery_scheduled_at:string;delivered_at:string|null;deadline_at:string|null;collected_at:string|null;status:string};
type Row={id:string;service_number:string;amount:number|string;payment_status:PaymentStatus;created_at:string;clients:{name:string}|null;client_addresses:{address:string;number:string|null;city:string}|null;service_payments:{amount:number|string;paid_at:string}[];service_dumpsters:Dumpster[]};
type Unit={service:Row;dumpster:Dumpster;number:number};type Metric={label:string;value:string;href:string;Icon:LucideIcon;wide?:boolean};
export const dynamic="force-dynamic";
export default async function Dashboard(){
 const sb=await createSupabaseServerClient();const{data:{user}}=await sb.auth.getUser();if(!user)redirect("/login");const{data:profile,error:profileError}=await sb.from("profiles").select("company_id,role").eq("id",user.id).single();if(profileError||!profile){console.error("[dashboard] Profile",profileError);throw new Error("Não foi possível validar o perfil do usuário.")}
 const paymentFields=profile.role==="admin"?",service_payments(amount,paid_at)":"";const{data:raw,error:servicesError}=await sb.from("services").select(`id,service_number,amount,payment_status,created_at,clients(name),client_addresses(address,number,city),service_dumpsters(id,delivery_scheduled_at,delivered_at,deadline_at,collected_at,status)${paymentFields}`).order("created_at",{ascending:false});if(servicesError){console.error("[dashboard] Serviços",servicesError);throw new Error("Não foi possível carregar o Dashboard.")}
 const rows=(raw||[]) as unknown as Row[],units:Unit[]=rows.flatMap(service=>(service.service_dumpsters||[]).map((dumpster,index)=>({service,dumpster,number:index+1}))),today=todayInSaoPaulo(),now=new Date();const{data:company,error:companyError}=await sb.from("companies").select("name").eq("id",profile.company_id).maybeSingle();if(companyError)console.error("[dashboard] Empresa",companyError);const companyName=company?.name?.trim()||"Nova Tira Entulho",{start,next}=monthBounds();
 const scheduled=units.filter(unit=>unit.dumpster.status==="scheduled"),deliveriesToday=scheduled.filter(unit=>dumpsterDayKey(unit.dumpster.delivery_scheduled_at)===today),atClients=units.filter(unit=>["delivered","waiting_collection"].includes(unit.dumpster.status)),collectionToday=atClients.filter(unit=>dumpsterDayKey(calculateDumpsterTiming(unit.dumpster,now).deadlineAt)===today);
 const pending=profile.role==="admin"?rows.filter(service=>service.service_dumpsters?.some(unit=>unit.status!=="cancelled")).reduce((sum,service)=>sum+Math.max(0,Number(service.amount)-(service.service_payments||[]).reduce((received,payment)=>received+Number(payment.amount),0)),0):0,paidMonth=profile.role==="admin"?rows.flatMap(service=>service.service_payments||[]).filter(payment=>payment.paid_at>=start&&payment.paid_at<next).reduce((sum,payment)=>sum+Number(payment.amount),0):0;
 const operationalMetrics:Metric[]=[{label:"Serviços agendados",value:String(scheduled.length),href:"/servicos?status=scheduled",Icon:CalendarCheck},{label:"Entregas de hoje",value:String(deliveriesToday.length),href:`/servicos?status=scheduled&date=${today}`,Icon:Truck},{label:"Retiradas de hoje",value:String(collectionToday.length),href:`/servicos?collection=${today}`,Icon:Undo2},{label:"Caçambas em clientes",value:String(atClients.length),href:"/servicos?statuses=delivered,waiting_collection",Icon:Container}],financialMetrics:Metric[]=[{label:"Valores a receber",value:money(pending),href:"/servicos?payments=receivable",Icon:Wallet,wide:true},{label:"Faturamento do mês",value:money(paidMonth),href:"/servicos?payments=month",Icon:TrendingUp,wide:true}],metrics=profile.role==="admin"?[...operationalMetrics,...financialMetrics]:operationalMetrics;
 const upcoming=atClients.map(unit=>({unit,timing:calculateDumpsterTiming(unit.dumpster,now)})).filter(item=>item.timing.deadlineAt).sort((a,b)=>new Date(a.timing.deadlineAt!).getTime()-new Date(b.timing.deadlineAt!).getTime()).slice(0,10);
 return <AppShell title="Visão geral"><div className="heading"><div><h1>Olá, {companyName}!</h1><div className="sub">Acompanhe a operação da sua empresa hoje.</div></div><Link className="btn" href="/servicos/novo">+ Novo serviço</Link></div><div className="grid">{metrics.map(({label,value,href,Icon,wide})=><Link className={`card metric metricLink dashboardMetric ${wide?"wide":""}`} href={href} key={label}><div><label>{label}</label><strong>{value}</strong></div><span className="metricIcon categoryIcon"><Icon size={20}/></span><ViewDetailsIndicator/></Link>)}</div><section className="section"><div className="sectionTitle"><h2>Próximas retiradas</h2><Link href="/servicos?statuses=delivered,waiting_collection">Ver todos <ArrowRight size={13} style={{display:"inline"}}/></Link></div>{upcoming.length===0?<div className="card emptyState">Nenhuma retirada programada.</div>:<div className="tableWrap withdrawalsTable"><table><thead><tr><th>Cliente / caçamba</th><th>Endereço</th><th>Entrega efetiva</th><th>Data limite</th><th>Prazo</th><th>Ações</th></tr></thead><tbody>{upcoming.map(({unit,timing})=>{const address=unit.service.client_addresses?`${unit.service.client_addresses.address}${unit.service.client_addresses.number?`, ${unit.service.client_addresses.number}`:""} · ${unit.service.client_addresses.city}`:"—";return <tr className="clickableRow" key={unit.dumpster.id}><td><Link className="rowLink" href={`/servicos/${unit.service.id}`}><b>{unit.service.clients?.name||"—"}</b><div className="sub">{unit.service.service_number} · Caçamba {unit.number}</div></Link></td><td>{address}</td><td>{date(timing.baseAt)}</td><td>{date(timing.deadlineAt)}</td><td className={`deadline ${timing.tone}`}>{timing.label}</td><td><ViewServiceLink id={unit.service.id} label="Ver detalhes"/></td></tr>})}</tbody></table></div>}</section></AppShell>;
}
